sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.8"
install:
  - pip install -e .[dev]
script:
  - echo "OK"
  - python -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
