version: '0.1'

settings:
  logging:
    time-format: "%H:%M:%S:%f"

services:
  web1:
    run: ruby ser1.rb
    cwd: examples
    color: blue
  web2_my_ruby_code:
    run: ruby ser2.rb
    cwd: examples
    color: green
  cat:
    run: head /etc/hosts
    color: yellow_2
  folly:
    run: echo "Gogo" && exit 1
    color: red_1
    shell: yes
    readiness:
      retry:
        attempts: 2
        wait: 1
