version: '1.0'

global:
  foo: 12

services:
  web1:
    run: ruby ser1.rb
    cwd: examples
    color: green
  web2_my_ruby_code:
    run: ruby ser2.rb
    cwd: examples
    color: cyan
  # cat:
  #   run: cat /etc/hosts
  #   color: blue
  # echo:
  #   run: echo 'OK'
