version: '0.1'

settings:
  time-format: "%H:%M:%S:%f"

services:
  web1:
    run: ruby ser1.rb
    cwd: examples
    color: green
  web2_my_ruby_code:
    run: ruby ser2.rb
    cwd: examples
    color: cyan
  cat:
    run: cat /etc/hosts
    color: yellow_2
  folly:
    run: echo "Gogo" && exit 7
    color: magenta
    shell: yes

# jobs:
#   cat:
#     run: cat /etc/hosts
#     color: blue
#   echo:
#     run: echo 'OK'
