name: Tests
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
          - 2.7
          - 3.9
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run unit tests
      run: python -m pytest tests/unit --color=yes --cov=./ --cov-report=xml

    - name: Run functional tests
      run: python -m pytest tests/functional --color=yes --cov=./ --cov-append --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        directory: ./coverage/reports/
        fail_ci_if_error: true
        verbose: false
